mathclubweb/contact/urls.py
from . import views
from django.urls import path
app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

mathclubweb/event/urls.py
from . import views
from django.urls import path
app_name = 'event'
urlpatterns = [
    path('event/', views.event, name='event'),
]

mathclubweb/formerpresi/urls.py
from . import views
from django.urls import path
app_name = 'formerpresi'
urlpatterns = [
    path('formerpresi/', views.president, name='formerpresi'),
]

mathclubweb/gallery/urls.py
from . import views
from django.urls import path
app_name = 'gallery'
urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
]

mathclubweb/home/urls.py
from . import views
from django.urls import path
app_name = 'home'
urlpatterns = [
    path('', views.home, name = 'home'), 
]

mathclubweb/joinus/urls.py
from . import views
from django.urls import path
app_name = 'joinus'
urlpatterns = [
    path('joinus/', views.joinus, name='joinus'),
]

mathclubweb/mathclubweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contactview/', include('contact.urls')),
    path('eventview/', include('event.urls')),
    path('formerpresiview/', include('formerpresi.urls')),
    path('galleryview/', include('gallery.urls')),
    path('', include('home.urls')),
    path('joinusview/', include('joinus.urls')),
    path('panelview/', include('panel.urls')),
    path('resourcesvies/', include('resource.urls')),
]

mathclubweb/panel/urls.py
from . import views
from django.urls import path
app_name = 'panel'
urlpatterns = [
    path('panel/', views.panel, name='panel'),
]

mathclubweb/resource/urls.py
from . import views
from django.urls import path
app_name = 'resource'
urlpatterns = [
    path('resource/', views.resource, name='resource'),
]

mathclubweb/contact/models.py
from django.db import models

# Create your models here.

mathclubweb/event/models.py
from django.db import models

# Create your models here.

mathclubweb/gallery/models.py
from django.db import models

# Create your models here.

mathclubweb/home/models.py
from django.db import models

# Create your models here.

mathclubweb/joinus/models.py
from django.db import models

# Create your models here.

mathclubweb/panel/models.py
from django.db import models

# Create your models here.

mathclubweb/contact/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request, 'contact/contact.html')

mathclubweb/event/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def event(request):
    return render(request, 'event/event.html')

mathclubweb/gallery/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def gallery(request):
    return render(request, 'gallery/gallery.html')

mathclubweb/home/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home/home.html')

mathclubweb/joinus/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def joinus(request):
    return render(request, 'joinus/join.html')

mathclubweb/panel/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def panel(request):
    return render(request, 'panel/panel.html')

mathclubweb/resource/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def resource(request):
    return render(request, 'resource/resource.html')

mathclubweb/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Math Club CSE UAP{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_css %}{% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="logo-container">
                <img src="{% static 'images/Math Club.png' %}" alt="Logo" class="logo">
                <span class="club-name">Math Club CSE</span>
            </div>
            <nav class="main-nav">
                <ul>
                    <li><a href="{% url 'home:home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a></li>
                    <li><a href="{% url 'event:event' %}" class="{% if request.resolver_match.url_name == 'event' %}active{% endif %}">Events</a></li>
                    <li><a href="{% url 'panel:panel' %}" class="{% if request.resolver_match.url_name == 'panel' %}active{% endif %}">Team</a></li>
                    <li><a href="{% url 'formerpresi:formerpresi' %}" class="{% if request.resolver_match.url_name == 'formerpresi' %}active{% endif %}">Former Presidents</a></li>
                    <li><a href="{% url 'gallery:gallery' %}" class="{% if request.resolver_match.url_name == 'gallery' %}active{% endif %}">Gallery</a></li>
                    <li><a href="{% url 'joinus:joinus' %}" class="{% if request.resolver_match.url_name == 'joinus' %}active{% endif %}">Join Us</a></li>
                    <li><a href="{% url 'resource:resource' %}" class="{% if request.resolver_match.url_name == 'resource' %}active{% endif %}">Resources</a></li>
                    <li><a href="{% url 'contact:contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">Contact</a></li>
                </ul>
            </nav>
            <div class="auth-links">
                <a href="#">Login</a>
                <a href="#">Register</a>
            </div>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer-main">
        <div class="logo-container-2">
                <img src="{% static 'images/Math Club.png' %}" alt="Logo" class="logo-2">
                <img src="{% static 'images/UAP.png' %}" alt="Logo" class="logo-3">
        </div>
        <div class="footer-container">
            <ul class="extra-links">
                <li><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'event:event' %}">Events</a></li>
                <li><a href="#">Privacy</a></li>
                <li><a href="#">Teams of Use</a></li>
            </ul>
             <ul class="social-links">
                <li>
                    <a href="https://web.facebook.com/mathclub.cse" target="_blank" class="social-icon">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
    <hr>
    <footer class="footer-sub">
        <div class="footer-info">
            <p>© 2026 Math Club All Rights Reserved | Developed by 
                <a href="https://www.facebook.com/Mominrifat09" target="_blank">Momin Ali Rifat</a>
            </p>
        </div>
    </footer>
</body>
</html>

mathclubweb/templates/resource/resource.html
{% extends "base.html" %} 

{% block content %}
    <h1>This is Resources page</h1>
    <p>This is page is under construction</p>
    <h1>    404 Not Fount  </h1>
{% endblock %}